# This is a basic workflow to help you get started with Actions

name: graphbot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  schedule:
  - cron: "0 4 * * *"  
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  graph:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: pip installs
        run: pip install matplotlib
        
      # Runs a single command using the runners shell
      - name: process the bioconda-stats
        run: python $GITHUB_WORKSPACE/scripts/update.py

      # Runs a set of commands using the runners shell
      - uses: actions/upload-artifact@v4
        with:
          name: downloads.png
          path: downloads.png
          compression-level: 0

      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -lR
          cp downloads.png $GITHUB_WORKSPACE/downloads.png
          git config user.name github-action
          git config user.email noreply@github.com
          git add downloads.png
          git commit -m 'update front image'
          git push
